### ISSUE TITLE
ReferenceError: dragonBones is not defined

### ISSUE THREAD

**Issue by footprint** [cocos-creator/example-cases#270] opened 2016-10-21 08:08 UTC
ReferenceError: dragonBones is not defined
at Object.require.DragonBonesCtrl: "requireComponent: dragonBones.ArmatureDisplay" (assets/cases/dragonbones/DragonBonesCtrl.js:20:8)
at s (../../../../../../Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/browser-pack/_prelude.js:1)
at e (../../../../../../Applications/CocosCreator.app/Contents/Resources/app.asar/node_modules/browser-pack/_prelude.js:1)
at file:///Users/footprint/Downloads/example-cases-master/library/bundle.project.js?001:1:451

**Comment by natural-law** [comment] 2016-10-21 09:36
What's the version of your Creator? And how did you create the example case project?
If you're using Creator 1.2, please don't use this repo directly. You should create example project from the Dashboard. 

Otherwise, please supply more details about how to reproduce the problem. Thanks for your feedback!

**Comment by nantas** [comment] 2016-11-24 03:59
It should be caused by incorrectly unchecked 'Dragon Bones' module from engine. And it should be fixed now.

**Closed by nantas** 2016-11-24 03:59 UTC
